version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules:cached
volumes:
  node_modules:
